--- !ruby/object:PluginManager::Config
name: ZVBattleLog
authors:
- zhec
version: 0.2.0.0
deps: []
psdk_compatibility_script: psdk.rb
retry_psdk_compatibility_after_plugin_load: false
added_files:
- Data/configs/plugins/zv_battle_log_config.json
- graphics/interface/zv-battle-log/**/*.png
